// Code generated by 'goexports github.com/osraige/visualisations/gauge'. DO NOT EDIT.

// +build go1.14,!go1.15

package goexports

import (
	"github.com/osraige/visualisations/gauge"
	"reflect"
)

func init() {
	Symbols["github.com/osraige/visualisations/gauge"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Gauge":  reflect.ValueOf(gauge.Gauge),
		"Gauges": reflect.ValueOf(gauge.Gauges),

		// type definitions
		"GaugeOptions": reflect.ValueOf((*gauge.GaugeOptions)(nil)),
	}
}
