// Code generated by 'goexports github.com/osraige/visualisations/clock'. DO NOT EDIT.

// +build go1.14,!go1.15

package goexports

import (
	"github.com/osraige/visualisations/clock"
	"reflect"
)

func init() {
	Symbols["github.com/osraige/visualisations/clock"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Clock": reflect.ValueOf(clock.Clock),

		// type definitions
		"ClockOptions": reflect.ValueOf((*clock.ClockOptions)(nil)),
	}
}
