// Code generated by 'goexports github.com/osraige/visualisations'. DO NOT EDIT.

// +build go1.14,!go1.15

package goexports

import (
	"github.com/osraige/visualisations"
	"reflect"
)

func init() {
	Symbols["github.com/osraige/visualisations"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CapStyleButt":          reflect.ValueOf(visualisations.CapStyleButt),
		"CapStyleRound":         reflect.ValueOf(visualisations.CapStyleRound),
		"CapStyleSquare":        reflect.ValueOf(visualisations.CapStyleSquare),
		"ParseDominantBaseline": reflect.ValueOf(visualisations.ParseDominantBaseline),
		"ParseFill":             reflect.ValueOf(visualisations.ParseFill),
		"ParseFillOpacity":      reflect.ValueOf(visualisations.ParseFillOpacity),
		"ParseFontFamily":       reflect.ValueOf(visualisations.ParseFontFamily),
		"ParseFontSize":         reflect.ValueOf(visualisations.ParseFontSize),
		"ParseStroke":           reflect.ValueOf(visualisations.ParseStroke),
		"ParseStrokeLineCap":    reflect.ValueOf(visualisations.ParseStrokeLineCap),
		"ParseStrokeOpacity":    reflect.ValueOf(visualisations.ParseStrokeOpacity),
		"ParseStrokeWidth":      reflect.ValueOf(visualisations.ParseStrokeWidth),
		"ParseStyles":           reflect.ValueOf(visualisations.ParseStyles),
		"ParseTextAnchor":       reflect.ValueOf(visualisations.ParseTextAnchor),
		"PointOnCircum":         reflect.ValueOf(visualisations.PointOnCircum),
		"ScaleRange":            reflect.ValueOf(visualisations.ScaleRange),

		// type definitions
		"CapStyle": reflect.ValueOf((*visualisations.CapStyle)(nil)),
	}
}
