// Code generated by 'goexports github.com/osraige/visualisations/timeline'. DO NOT EDIT.

// +build go1.14,!go1.15

package goexports

import (
	"github.com/osraige/visualisations/timeline"
	"reflect"
)

func init() {
	Symbols["github.com/osraige/visualisations/timeline"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetTruncatedEntryLabel": reflect.ValueOf(timeline.GetTruncatedEntryLabel),
		"Timeline":               reflect.ValueOf(timeline.Timeline),

		// type definitions
		"TimelineOptions": reflect.ValueOf((*timeline.TimelineOptions)(nil)),
	}
}
