// Code generated by 'goexports github.com/ajstarks/svgo/float'. DO NOT EDIT.

// +build go1.14,!go1.15

package goexports

import (
	"reflect"

	svg "github.com/ajstarks/svgo/float"
)

func init() {
	Symbols["github.com/ajstarks/svgo/float"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New": reflect.ValueOf(svg.New),

		// type definitions
		"Filterspec": reflect.ValueOf((*svg.Filterspec)(nil)),
		"Offcolor":   reflect.ValueOf((*svg.Offcolor)(nil)),
		"SVG":        reflect.ValueOf((*svg.SVG)(nil)),
	}
}
